-- NUMBER CONSTRAINT ID_MY_DEVICE PRIMARY KEY
CREATE TABLE MY_DEVICE (
ID bigint auto_increment,
CODICE_FISCALE VARCHAR,
OS VARCHAR,
OS_VERSION VARCHAR,
BUNDLE_ID VARCHAR,
APP_VERSION VARCHAR,
BUILD VARCHAR,
DEVICE_TOKEN VARCHAR,
APP_ID VARCHAR,
LOCAL VARCHAR,
DT_REG TIMESTAMP
);
